### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by ipiedrahiv** [torrua/loglan_db#4]
Hi!

I've notices that you have an unused variable in loglan_db/model_db/addons/addon_word_sourcer.py named which_prims. Could I remove it?

It is my first PR to an open source repo so I'd aprriciate any comments and suggestions if you give me permission to delete it :)

Thank you

**Comment by torrua** [comment]
Hi, @ipiedrahiv!
Thank you for your attention to this project. This variable stores important data. I'll move it to the docs later. So this variable does not need to be deleted yet.

Thank you!
